appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: n0yAoJgrrUn/00f2xKfjj7VJ1hB5Dr0zy3JvDO9AX90Uu8dDYtaXn17vytXtPmkq3Fm0pzGioxPDNzsVhOJLtxHMwpKTKj2Cfb5lvbINnzxwdmjaKMtNMVfRQ4arrLzAwsUTaBkr3+k2OMA0Fv0MNRNu61SSiUhP9lddof0rxobG2BnbgfhFWJUNZ/tEp0HLAoqKSEh7nCeMNZJOdGAjnB2k36Llqxznb++ggRVzFyUGsW1b7CgDawgxR+q/ccRaM8/S7GJzIbGhXJIw/2o685xi/BbULwLRq0wzLPakepWyll0dfYYqF7xZm861rrckmvjlyy7b4TbTGLPLlZehlRgDmX52TnQiADUEaGh0i3ldqwVvl1eJ0e+CczyHJI0i93r+oXOcg4s32WznXZwgteYwx3NEe/zSWyCSUo14L+8fNEUS5YQZRq+k2mp89dDKfk1eoKiP975QespmTSwqFoPTjKQAr6CKGURXa5tJHp8z7MgxVsEGaq+P4A31vG1spWTEf54wM+FK4QS4TkaNr70GZVNgDjIFgYsdVmlUu+QKMvD4MgVPNLiXz/a8FrwIXFi1DlTLeG4naKtdw8cIXubz9NHWY8WDj7yB8yeHs5NKlUSoN+vbc7myqmIZnt4mX1UA+xU0esKuvh4pZKMGX62Ej97nGYmMnrFP/J0bhxE=
